import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {marked} from './vendor/marked.mjs';
import {readingList, bookCategories} from './reading-list.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.join(root,'docs');
const read=async p=>fs.readFile(path.join(root,p),'utf8');
const site=JSON.parse(await read('content/site.json'));
const papers=JSON.parse(await read('content/papers.json'));
const bookYears=readingList(JSON.parse(await read('content/books.json')));
const parsePost=(raw,file)=>{const match=raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);if(!match)throw new Error(`Missing metadata in ${file}`);const p={file,slug:file.replace(/\.md$/,'')};for(const line of match[1].split('\n')){const pair=line.match(/^([a-zA-Z]+):\s*(.*)$/);if(!pair||line.startsWith('#'))continue;try{p[pair[1]]=JSON.parse(pair[2]);}catch{p[pair[1]]=pair[2];}}if(!p.title||!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||Number.isNaN(new Date(p.date).getTime()))throw new Error(`Invalid title/date in ${file}`);return {...p,rawBody:match[2]};};
const meta=[];for(const file of await fs.readdir(path.join(root,'content/posts'))){if(file.endsWith('.md'))meta.push(parsePost(await read('content/posts/'+file),file));}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=s=>s.replace(/<[^>]*>/g,' ').replace(/!\[[^\]]*\]\([^)]+\)/g,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/[*_`#>]/g,'').replace(/\s+/g,' ').trim();
const date=(d,opts)=>new Intl.DateTimeFormat('en-US',{timeZone:'UTC',...opts}).format(new Date(d+'T12:00:00Z'));
const href=p=>`blog/${p.slug}/`;
const cleanBody=md=>{const match=md.match(/^\*\*\d{4}-\d{2}-\d{2}\*\*[^\n]*\n\s*---\s*\n([\s\S]*)/m);let body=match?match[1]:md;body=body.split(/\n---\s*\n\s*<p align="center">/)[0];return body.trim();};
const posts=[];
for(const p of meta){if(p.featured===false)continue;if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug))throw new Error('Invalid post slug: '+p.slug);const body=cleanBody(p.rawBody);let html=marked.parse(body,{gfm:true,breaks:false});html=html.replace(/href="([^"/]+)\.md(?:#[^"]*)?"/g,(_,slug)=>`href="../${esc(slug)}/"`);const words=text(body).split(/\s+/).length;posts.push({...p,body,html,readingTime:Math.max(1,Math.ceil(words/220)),excerpt:p.excerpt||''});}
posts.sort((a,b)=>b.date.localeCompare(a.date)||a.slug.localeCompare(b.slug));
await fs.rm(out,{recursive:true,force:true});await fs.mkdir(out,{recursive:true});await fs.cp(path.join(root,'public'),out,{recursive:true});
const write=async(p,s)=>{const dest=path.join(out,p);await fs.mkdir(path.dirname(dest),{recursive:true});await fs.writeFile(dest,s);};
const head=(title,description,base,canonical,reading=false)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${site.origin}${canonical}"><meta name="theme-color" content="#3568bf"><link rel="icon" type="image/svg+xml" href="${base}assets/favicon.svg"><link rel="stylesheet" href="${base}assets/site.css">${reading?'<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css"><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"></script><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js" onload="renderMathInElement(document.querySelector(\'.article-body\'),{delimiters:[{left:\'$$\',right:\'$$\',display:true},{left:\'\\\\[\',right:\'\\\\]\',display:true},{left:\'\\\\(\',right:\'\\\\)\',display:false},{left:\'$\',right:\'$\',display:false}],throwOnError:false})"></script>':''}</head>`;
const header=(active,base='')=>`<header class="site-header"><a class="wordmark" href="${base||'./'}">Yumi Omori</a><nav class="main-nav" aria-label="Main navigation"><a href="${base||'./'}"${active==='research'?' aria-current="page"':''}>Research</a><a href="${base}personal/"${active==='personal'?' aria-current="page"':''}>Personal</a></nav></header>`;
const footer='';
const paperHTML=papers.length?papers.map(p=>`<article class="paper-item"><h3>${esc(p.title)}</h3><p>${esc(p.authors)}</p><p>${esc(p.venue)}</p>${p.url?`<a href="${esc(p.url)}">Paper</a>`:''}</article>`).join(''):'';
await write('index.html',head('Yumi Omori',site.introduction,'','/')+`<body><a class="skip-link" href="#main">Skip to content</a><div class="shell">${header('research')}<main id="main"><section class="intro"><div><p>${esc(site.title)} ${esc(site.introduction)} ${esc(site.note)}</p><p>Here are my works:</p></div><img class="profile" src="${esc(site.photo)}" alt="Yumi Omori" width="136" height="136"></section><section class="papers" aria-label="Research works">${paperHTML}</section></main>${footer}</div></body></html>`);
const months=[...new Set(posts.map(p=>p.date.slice(0,7)))];
const monthId=m=>'month-'+m;
const asset=(p,base)=>/^https?:\/\//.test(p)?esc(p):base+esc(p);
const cards=m=>posts.filter(p=>p.date.startsWith(m)).map(p=>`<article class="post-card${p.cover?' has-cover':''}">${p.cover?`<a class="cover-link" href="../${href(p)}" tabindex="-1" aria-hidden="true"><img class="post-cover" src="${asset(p.cover,'../')}" alt="" loading="lazy" width="156" height="120"></a>`:''}<div><p class="card-date"><time datetime="${p.date}">${date(p.date,{month:'long',day:'numeric',year:'numeric'})}</time></p><h2><a href="../${href(p)}">${esc(p.title)}</a></h2>${p.excerpt?p.excerpt.split(/\n\s*\n/).map(paragraph=>`<p class="excerpt">${esc(paragraph)}</p>`).join(''):''}</div></article>`).join('');
const timeline=months.map((m,i)=>`<a class="timeline-link" href="#${monthId(m)}"${i===0?' aria-current="true"':''}><span>${date(m+'-01',{month:'short',year:'numeric'})}</span><span class="tick" aria-hidden="true"></span></a>`).join('');
await write('personal/index.html',head('Personal · Yumi Omori','A subset of the things I write.','../','/personal/')+`<body><a class="skip-link" href="#main">Skip to content</a><div class="shell">${header('personal','../')}<main id="main"><div class="personal-intro"><p>I <a href="../travel/">travel</a>, <a href="../read/">read</a>, write a lot. I also played a lot of video games. Below are a subset of the things I write. While some of the titles might interest you, many of the posts contain personal content as well. This page serves as a personal archive for me to organize my life.</p></div><div class="archive-layout"><div class="post-list">${months.map(m=>`<section class="month-group" id="${monthId(m)}" aria-label="${date(m+'-01',{month:'long',year:'numeric'})}">${cards(m)}</section>`).join('')}</div><nav class="timeline" aria-label="Browse posts by month">${timeline}</nav></div></main>${footer}</div><script src="../assets/timeline.js" defer></script></body></html>`);
for(let i=0;i<posts.length;i++){const p=posts[i],older=posts[i+1],newer=posts[i-1];const nav=(item,label,cls)=>item?`<a class="${cls}" href="../${item.slug}/" rel="${cls==='previous'?'prev':'next'}"><span class="nav-label">${label}</span><span class="nav-title">${esc(item.title)}</span></a>`:'<span aria-hidden="true"></span>';await write(href(p)+'index.html',head(p.title+' · Yumi Omori',p.excerpt||p.title,'../../','/'+href(p),true)+`<body class="reading-page"><a class="skip-link" href="#article">Skip to article</a><main class="reading-main" id="article"><article><header class="article-header"><h1>${esc(p.title)}</h1><ul class="article-meta"><li><a href="../../">Yumi Omori</a></li><li><time datetime="${p.date}">${date(p.date,{month:'long',year:'numeric'})}</time></li></ul></header><div class="article-body">${p.html}</div></article><nav class="post-navigation" aria-label="Article navigation">${nav(older,'Previous post','previous')}${nav(newer,'Next post','next')}</nav><a class="back-to-blog" href="../../personal/#${monthId(p.date.slice(0,7))}">Back to blog</a></main></body></html>`);}
await write('travel/index.html',head('Travel · Yumi Omori','Travel.','../','/travel/')+`<body><a class="skip-link" href="#main">Skip to content</a><div class="shell">${header('personal','../')}<main id="main" class="travel-page"><p>Travel</p><a class="travel-back" href="../personal/">Back to blog</a></main></div></body></html>`);
const catalogueCount=bookYears.reduce((n,y)=>n+y.books.length,0);
const bookHTML=book=>`<li class="book" data-id="${esc(book.id)}" data-search="${esc([book.title,book.englishTitle,book.author,book.englishAuthor].filter(Boolean).join(' '))}"><p class="book-title" lang="${esc(book.language)}">${esc(book.title)}</p>${book.englishTitle&&book.englishTitle!==book.title?`<p class="book-translation" lang="en">${esc(book.englishTitle)}</p>`:''}${book.author?`<p class="book-author"><span lang="${esc(book.language)}">${esc(book.author)}</span>${book.englishAuthor&&book.englishAuthor!==book.author?` <span lang="en">· ${esc(book.englishAuthor)}</span>`:''}</p>`:''}</li>`;
const shelfHTML=({year,books})=>`<section class="book-year" id="year-${year}" aria-labelledby="heading-${year}"><div class="year-heading"><h2 id="heading-${year}">${year ?? 'Undated'}</h2><span class="year-count">${books.length} books</span></div>${bookCategories.map(category=>{const entries=books.filter(b=>b.category===category.id);return entries.length?`<section class="book-category" data-category="${category.id}" aria-labelledby="category-${year}-${category.id}"><div class="category-heading"><h3 id="category-${year}-${category.id}">${esc(category.label)}</h3>${category.description?`<span class="category-description">${esc(category.description)}</span>`:''}<span class="category-count">${entries.length}</span></div><ul class="book-list">${entries.map(bookHTML).join('')}</ul></section>`:'';}).join('')}</section>`;
await write('read/index.html',head('Reading · Yumi Omori','My reading list, organized by year and theme.','../','/read/')+`<body class="library-page"><a class="skip-link" href="#main">Skip to content</a><div class="shell library-shell">${header('personal','../')}<main id="main" class="books-page" aria-label="Reading list"><header class="library-intro"><div><h1 class="sr-only">Reading list</h1><p class="books-intro">My reading list, organized by year and theme.</p></div><a class="books-back" href="../personal/">back to writing</a></header><div class="book-tools" hidden><label class="book-search"><span class="sr-only">Find a title or author</span><input id="book-search" type="search" placeholder="Find a title or author" autocomplete="off"></label><label class="book-theme"><span class="sr-only">Filter by theme</span><select id="book-theme"><option value="all">All themes</option>${bookCategories.map(c=>`<option value="${c.id}">${esc(c.label)}</option>`).join('')}</select></label><span id="book-results" role="status" aria-live="polite">${catalogueCount} books</span></div><div class="library-layout"><div class="book-shelves">${bookYears.map(shelfHTML).join('')}<p class="books-empty" hidden>No books match your search.</p></div><nav class="timeline book-years" aria-label="Browse books by year">${bookYears.map(({year},i)=>`<a class="timeline-link" href="#year-${year}"${i===0?' aria-current="true"':''}><span>${year ?? 'Undated'}</span><span class="tick" aria-hidden="true"></span></a>`).join('')}</nav></div><a class="books-back" href="../personal/">back to writing</a></main></div><script src="../assets/books.js" defer></script></body></html>`);
await write('404.html',head('Page not found · Yumi Omori','Page not found.','/','/404.html')+'<body><main class="reading-main"><h1>Page not found</h1><p><a href="/">Research</a> · <a href="/personal/">Personal</a></p></main></body></html>');
await write('.nojekyll','');await write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${site.origin}/sitemap.xml\n`);
await write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['/','/personal/','/travel/','/read/',...posts.map(p=>'/'+href(p))].map(p=>`<url><loc>${esc(site.origin+p)}</loc></url>`).join('')+'</urlset>');
console.log(`Built research homepage, personal blog, and ${posts.length} complete articles in docs/.`);

