import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {marked} from './vendor/marked.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.join(root,'docs');
const read=async p=>fs.readFile(path.join(root,p),'utf8');
const site=JSON.parse(await read('content/site.json'));
const papers=JSON.parse(await read('content/papers.json'));
const parsePost=(raw,file)=>{const match=raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);if(!match)throw new Error(`Missing metadata in ${file}`);const p={file,slug:file.replace(/\.md$/,'')};for(const line of match[1].split('\n')){const pair=line.match(/^([a-zA-Z]+):\s*(.*)$/);if(!pair||line.startsWith('#'))continue;try{p[pair[1]]=JSON.parse(pair[2]);}catch{p[pair[1]]=pair[2];}}if(!p.title||!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||Number.isNaN(new Date(p.date).getTime()))throw new Error(`Invalid title/date in ${file}`);return {...p,rawBody:match[2]};};
const meta=[];for(const file of await fs.readdir(path.join(root,'content/posts'))){if(file.endsWith('.md'))meta.push(parsePost(await read('content/posts/'+file),file));}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=s=>s.replace(/<[^>]*>/g,' ').replace(/!\[[^\]]*\]\([^)]+\)/g,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/[*_`#>]/g,'').replace(/\s+/g,' ').trim();
const date=(d,opts)=>new Intl.DateTimeFormat('en-US',{timeZone:'UTC',...opts}).format(new Date(d+'T12:00:00Z'));
const href=p=>`blog/${p.slug}/`;
const cleanBody=md=>{const match=md.match(/^\*\*\d{4}-\d{2}-\d{2}\*\*[^\n]*\n\s*---\s*\n([\s\S]*)/m);let body=match?match[1]:md;body=body.split(/\n---\s*\n\s*<p align="center">/)[0];return body.trim();};
const posts=[];
for(const p of meta){if(p.featured===false)continue;if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug))throw new Error('Invalid post slug: '+p.slug);const body=cleanBody(p.rawBody);let html=marked.parse(body,{gfm:true,breaks:false});html=html.replace(/href="([^"/]+)\.md(?:#[^"]*)?"/g,(_,slug)=>`href="../${esc(slug)}/"`);const words=text(body).split(/\s+/).length;posts.push({...p,body,html,readingTime:Math.max(1,Math.ceil(words/220)),excerpt:p.excerpt||text(body).slice(0,215).replace(/\s+\S*$/,'')+'…'});}
posts.sort((a,b)=>b.date.localeCompare(a.date)||a.slug.localeCompare(b.slug));
await fs.rm(out,{recursive:true,force:true});await fs.mkdir(out,{recursive:true});await fs.cp(path.join(root,'public'),out,{recursive:true});
const write=async(p,s)=>{const dest=path.join(out,p);await fs.mkdir(path.dirname(dest),{recursive:true});await fs.writeFile(dest,s);};
const head=(title,description,base,canonical,reading=false)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${site.origin}${canonical}"><meta name="theme-color" content="#3568bf"><link rel="icon" type="image/svg+xml" href="${base}assets/favicon.svg"><link rel="stylesheet" href="${base}assets/site.css">${reading?'<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css"><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"></script><script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js" onload="renderMathInElement(document.querySelector(\'.article-body\'),{delimiters:[{left:\'$$\',right:\'$$\',display:true},{left:\'\\\\[\',right:\'\\\\]\',display:true},{left:\'\\\\(\',right:\'\\\\)\',display:false},{left:\'$\',right:\'$\',display:false}],throwOnError:false})"></script>':''}</head>`;
const header=(active,base='')=>`<header class="site-header"><a class="wordmark" href="${base||'./'}">Yumi Omori</a><nav class="main-nav" aria-label="Main navigation"><a href="${base||'./'}"${active==='research'?' aria-current="page"':''}>Research</a><a href="${base}personal/"${active==='personal'?' aria-current="page"':''}>Personal</a></nav></header>`;
const footer=`<footer class="site-footer">Yumi Omori</footer>`;
const paperHTML=papers.length?papers.map(p=>`<article class="paper-item"><h3>${esc(p.title)}</h3><p>${esc(p.authors)}</p><p>${esc(p.venue)}</p>${p.url?`<a href="${esc(p.url)}">Paper</a>`:''}</article>`).join(''):'<p class="papers-empty">Coming soon.</p>';
await write('index.html',head('Yumi Omori',site.introduction,'','/')+`<body><a class="skip-link" href="#main">Skip to content</a><div class="shell">${header('research')}<main id="main"><section class="intro"><div><h1>${esc(site.title).replace('Yumi.','<span>Yumi.</span>')}</h1><p>${esc(site.introduction)}</p><p class="note">${esc(site.note)}</p></div><img class="profile" src="${esc(site.photo)}" alt="Yumi Omori" width="198" height="238"></section><section class="papers" aria-labelledby="papers-heading"><h2 class="section-heading" id="papers-heading">Papers</h2>${paperHTML}</section></main>${footer}</div></body></html>`);
const months=[...new Set(posts.map(p=>p.date.slice(0,7)))];
const monthId=m=>'month-'+m;
const cards=m=>posts.filter(p=>p.date.startsWith(m)).map(p=>`<article class="post-card${p.cover?' has-cover':''}">${p.cover?`<a class="cover-link" href="../${href(p)}" tabindex="-1" aria-hidden="true"><img class="post-cover" src="../${esc(p.cover)}" alt="" loading="lazy" width="200" height="220"></a>`:''}<div><p class="card-date"><time datetime="${p.date}">${date(p.date,{month:'long',day:'numeric',year:'numeric'})}</time> <span aria-hidden="true">·</span> ${p.readingTime} min read</p><h2><a href="../${href(p)}">${esc(p.title)}</a></h2><p class="excerpt">${esc(p.excerpt)}</p><a class="read-more" href="../${href(p)}" aria-label="Read ${esc(p.title)}">Read more</a></div></article>`).join('');
const timeline=months.map((m,i)=>`<a class="timeline-link" href="#${monthId(m)}"${i===0?' aria-current="true"':''}><span>${date(m+'-01',{month:'short',year:'numeric'})}</span><span class="tick" aria-hidden="true"></span></a>`).join('');
await write('personal/index.html',head('Personal · Yumi Omori','Featured writing by Yumi Omori.','../','/personal/')+`<body><a class="skip-link" href="#main">Skip to content</a><div class="shell">${header('personal','../')}<main id="main"><div class="archive-heading"><p class="eyebrow">Personal</p><h1>Featured writing</h1></div><div class="archive-layout"><div class="post-list">${months.map(m=>`<section class="month-group" id="${monthId(m)}" aria-label="${date(m+'-01',{month:'long',year:'numeric'})}">${cards(m)}</section>`).join('')}</div><nav class="timeline" aria-label="Browse posts by month"><p class="timeline-label">Timeline</p>${timeline}</nav></div></main>${footer}</div><script src="../assets/timeline.js" defer></script></body></html>`);
for(let i=0;i<posts.length;i++){const p=posts[i],older=posts[i+1],newer=posts[i-1];const nav=(item,label,cls)=>item?`<a class="${cls}" href="../${item.slug}/" rel="${cls==='previous'?'prev':'next'}"><span class="nav-label">${label}</span><span class="nav-title">${esc(item.title)}</span></a>`:'<span aria-hidden="true"></span>';await write(href(p)+'index.html',head(p.title+' · Yumi Omori',p.excerpt,'../../','/'+href(p),true)+`<body class="reading-page"><a class="skip-link" href="#article">Skip to article</a><main class="reading-main" id="article"><article><header class="article-header"><h1>${esc(p.title)}</h1><ul class="article-meta"><li><a href="../../">Yumi Omori</a></li><li><time datetime="${p.date}">${date(p.date,{month:'long',year:'numeric'})}</time></li></ul></header><div class="article-body">${p.html}</div></article><nav class="post-navigation" aria-label="Article navigation">${nav(older,'Previous post','previous')}${nav(newer,'Next post','next')}</nav><a class="back-to-blog" href="../../personal/#${monthId(p.date.slice(0,7))}">Back to blog</a></main></body></html>`);}
await write('404.html',head('Page not found · Yumi Omori','Page not found.','/','/404.html')+'<body><main class="reading-main"><h1>Page not found</h1><p><a href="/">Research</a> · <a href="/personal/">Personal</a></p></main></body></html>');
await write('.nojekyll','');await write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${site.origin}/sitemap.xml\n`);
await write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['/','/personal/',...posts.map(p=>'/'+href(p))].map(p=>`<url><loc>${esc(site.origin+p)}</loc></url>`).join('')+'</urlset>');
console.log(`Built research homepage, featured archive, and ${posts.length} complete articles in docs/.`);
